version: '3.8'

services:
  db:
    image: postgres:15
    container_name: padel_postgres
    restart: always
    environment:
      POSTGRES_USER: padel_user
      POSTGRES_PASSWORD: padel_pass
      POSTGRES_DB: padel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: padel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: padel_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: padel_user
      DB_PASS: padel_pass
      DB_HOST: db
      DB_NAME: padel_db
      DB_PORT: 5432
      PORT: 5001
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "start"]

  frontend:
    build: ./frontend
    container_name: padel_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
